notifications:
  slack: wsi-t113:SRHSOd3CgFDUwFxqv8SCXuIf
  email: false

sudo: false

language: ruby

services:
 - docker

script:
 - echo 'Build and check docker image'
 - docker build -t fastqc .
 - docker images | grep -c fastqc
 - echo 'Verify program(s) from this repo'
 - docker run -t --rm fastqc fastqc -h
 - docker run -v $PWD/test/:/tmp/test -t --rm fastqc fastqc /tmp/test/test.fq
