notifications:
  slack: wsi-t113:SRHSOd3CgFDUwFxqv8SCXuIf
  email: false

language: ruby

os: linux

services:
 - docker

script:
 - echo 'Build and check docker image'
 - docker build -t fastqc .
 - docker images | grep -c fastqc
 - echo 'Verify program(s) from this repo'
 - docker run -t --rm fastqc fastqc -h
 - ls -lrt ${TRAVIS_BUILD_DIR}/test
 - docker run -v ${TRAVIS_BUILD_DIR}/test:/tmp/test -t --rm fastqc fastqc /tmp/test/test.fq
 - if [ -f ${TRAVIS_BUILD_DIR}/test_fastqc.zip ]; then echo "FastQC results exist" || travis_terminate 0 
